apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: faas-pubsub
  namespace: {{ .Values.namespace }}
spec:
  metadata:
  - name: brokers
    value: kafka.lowcode.svc.cluster.local:9092
  - name: authRequired
    value: "false"
  - name: maxMessageBytes
    value: 1024
  type: pubsub.kafka
  version: v1
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: faas-dapr
  namespace: {{ .Values.namespace }}
scopes:
- faas-dapr
spec:
  pubsubname: faas-pubsub
  routes:
    default: /event
  topic: lowcode.faas